name: Setup
description: Common setup steps for kpv workflows

inputs:
  dependencies-command:
    description: Command to prepare project dependencies
    required: false
    default: 'cargo fetch --locked'

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache cargo artifacts
      uses: Swatinem/rust-cache@v2

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Install dependencies
      if: inputs.dependencies-command != ''
      run: ${{ inputs.dependencies-command }}
      shell: bash
